FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Searchflight

Searchflight is a robust API that enables you integrate flights search and bookings into your app.


## Authentication [/api/v1/tokens]

### Get Token [POST]

SearchFlight uses apikey to enable access it's api. To have access to api key, contact us.
Api key gotten generates an authorization token, which must be included in all requests as a header.

+ Request (application/json)
    + Body
    
            {
                "apiKey": "lQKF8n1KVYezN7MDTMqxhXGrZCfgRDvQ"
             }

+ Response 201 (application/json)


    + Body

            {
                "status": "200",
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQwLCJuYW1lIjoic2F2YW5hIHNtYXJ0c2F2ZSIsImFjY291bnROdW1iZ"
            }
            
+ Response 404 (application/json)


    + Body

            {
                "status": "404",
                "data": "App key is not valid"
            }


## Get city code from name [/api/v1/cities]

### Get city code from name [POST]
With this endpoint you can get the IATA city codes associated with a particular city name.

+ Request (application/json, )
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQwLCJuYW1lIjoic2F2YW5hIHNtYXJ0c2F2ZSIsImFjY291bnROdW1iZ

    + Body
                    
            {
                 "cityName": "Uyo"
            }
+ Response 201 (application/json)


    + Body

            {
                "status": "200",
                "data": [
                    {
                        "cityCode": "QUO",
                        "cityName": "Uyo",
                        "airport":"Ibom International Airport",
                        "country": "Nigeria"
                        
                    }, {
                        "cityCode": "PSR",
                        "cityName": "Uyo",
                        "airport":"Beis Airport",
                        "country": "Switzerland"
                    }, {
                        "cityCode": "WDV",
                        "cityName": "Uyo",
                        "airport":"Algeria Intl",
                        "country": "Algeria"
                    }
                ]
            }
+ Response 401 (application/json)


    + Body

            {
                "status": "401",
                "data": "Unauthorized access"
            }
+ Response 404 (application/json)


    + Body

            {
                "status": "404",
                "data": "City does not exist"
            }


## Get city name from code [/api/v1/cities/{cityCode}]

### Get city name from code [POST]
With this endpoint you can get the city name associated with an IATA Code.
Searchflight expects for a authorization token to be included in all requests as a header.
+ Request (application/json, )
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQwLCJuYW1lIjoic2F2YW5hIHNtYXJ0c2F2ZSIsImFjY291bnROdW1iZ
            

+ Response 201 (application/json)


    + Body

            {
                "status": "200",
                "data": [
                    {
                        "cityCode": "QUO",
                        "cityName": "Uyo",
                        "country": "Nigeria"
                        
                    }
                ]
            }
+ Response 401 (application/json)


    + Body

            {
                "status": "401",
                "data": "Unauthorized access"
            }
+ Response 404 (application/json)


    + Body

            {
                "status": "404",
                "data": "City code does not exist"
            }
## Search One way Flight [/api/v1/search/flights/{oneWay}]

### Search one way flight [POST]
With this endpoint you can search for one way flights from a location.
+ Request (application/json, )
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQwLCJuYW1lIjoic2F2YW5hIHNtYXJ0c2F2ZSIsImFjY291bnROdW1iZ
            

    + Body
                    
            {
                 "origin": "QUO",
                 "destination":"LOS",
                 "departure":"2017-10-04",
                 "options": [
                 {"times":{
                    "depart":"11:30",
                    "return":"15:00"
                    }
                 },
                 {"price":{
                    "currency":"NGN",
                    "below":"50,000"
                    }
                 },
                 {"airline":{
                    "carrierCode":"W3",
                    "carrierName":"Arik Airline",
                    "cabin":"first class"
                    }
                 },
                 {"passengers": {
                      "adultCount": 1,
                      "infantInLapCount": 0,
                      "infantInSeatCount": 0,
                      "childCount": 0,
                      "seniorCount": 0
                    }
                 },
                 {"extras":{
                     "stops":"0",
                     "refundable":"true"
                     }
                }
                ]
                 
            }
+ Response 201 (application/json)


    + Body

            {
                "status": "200",
                "data": [
                {
                    "stops":0,
                    "trip":{
                            
                            "aircraft":{
                                "code":"767",
                                "name":"Boeing 737"
                                },
                            "departure":{
                                "cityCode":"LOS",
                                "cityName":"Lagos",
                                "airport":"Lagos Murtaka Muhammed International"
                                },
                            "arrival":{
                                "cityCode":"ABV",
                                "cityName":"Abuja",
                                "airport":"Abuja Nnamd Azikiwe International"
                                },
                            
                            "booking":{
                                "id":"GI5njCtlByOCiRu4",
                                "code":"O",
                                "codeCount":9
                                },
                            "times":{
                                "departure":"2017-10-04T18:00+01:00",
                                "arrival":"2017-10-04T19:00+01:00",
                                "duration":68
                                },
                            {
                                "departure":"2017-10-04T20:00+01:00",
                                "arrival":"2017-10-04T21:00+01:00",
                                "duration":68
                                },
                            "pricing":{
                                "baseFare":"USD100",
                                "salesFare":"NGN35983",
                                "salesTax":"NGN19701",
                                "saleTotal":"NGN55684"
                                },
                            "tax":[
                                    {
                                        "id":"JY_002",
                                        "chargeType":"GOVERNMENT",
                                        "chargeCode":"JY",
                                        "country":"NG",
                                        "salePrice":"NGN1799"
                                    },
                                    {
                                        "id":"QT_001",
                                        "chargeType":"CARRIER_SURCHARGE",
                                        "chargeCode":"QT",
                                        "country":"NG",
                                        "salePrice":"NGN2345"
                                    }
                                ],
                            "carrier":{
                                "code":"H1",
                                "name":"Hahn Air System"
                                },
                            "cabin":"ECONOMY",
                            "mileage":"317",
                            "operating disclosure":"Operated by medview airlines",
                            "latestTicketingTime":"2017-10-04T20:00+01:00"
                            
                    }
                },
                {
                    "stops":2,
                    "trip1":{
                            
                            "aircraft":{
                                "code":"767",
                                "name":"Boeing 737"
                                },
                            "departure":{
                                "cityCode":"LOS",
                                "cityName":"Lagos",
                                "airport":"Lagos Murtaka Muhammed International"
                                },
                            "arrival":{
                                "cityCode":"ABV",
                                "cityName":"Abuja",
                                "airport":"Abuja Nnamd Azikiwe International"
                                },
                            
                            "booking":{
                                "id":"GI5njCtlByOCiRu4",
                                "code":"O",
                                "codeCount":9
                                },
                            "times":{
                                "departure":"2017-10-04T18:00+01:00",
                                "arrival":"2017-10-04T19:00+01:00",
                                "duration":68
                                },
                            "pricing":{
                                "baseFare":"USD100",
                                "salesFare":"NGN35983",
                                "salesTax":"NGN19701",
                                "saleTotal":"NGN55684"
                                },
                            "tax":[
                                    {
                                        "id":"JY_002",
                                        "chargType":"GOVERNMENT",
                                        "chargeCode":"JY",
                                        "country":"NG",
                                        "salePrice":"NGN1799"
                                    },
                                    {
                                        "id":"QT_001",
                                        "chargeType":"CARRIER_SURCHARGE",
                                        "chargeCode":"QT",
                                        "country":"NG",
                                        "salePrice":"NGN2345"
                                    }
                                ],
                            "carrier":{
                                "code":"H1",
                                "name":"Hahn Air System"
                                },
                            "cabin":"ECONOMY",
                            "mileage":"317",
                            "operatingDisclosure":"Operated by medview airlines",
                            "latestTicketingTime":"2017-10-04T20:00+01:00"
                            
                    },
                    "trip2":{
                            
                            "aircraft":{
                                "code":"767",
                                "name":"Boeing 737"
                                },
                            "departure":{
                                "cityCode":"LOS",
                                "cityName":"Lagos",
                                "airport":"Lagos Murtaka Muhammed International"
                                },
                            "arrival":{
                                "cityCode":"ABV",
                                "cityName":"Abuja",
                                "airport":"Abuja Nnamd Azikiwe International"
                                },
                            
                            "booking":{
                                "id":"GI5njCtlByOCiRu4",
                                "code":"O",
                                "codeCount":9
                                },
                            "times":{
                                "departure":"2017-10-04T18:00+01:00",
                                "arrival":"2017-10-04T19:00+01:00",
                                "duration":68
                                },
                            "pricing":{
                                "baseFare":"USD100",
                                "salesFare":"NGN35983",
                                "salesTax":"NGN19701",
                                "saleTotal":"NGN55684"
                                },
                            "tax":[
                                    {
                                        "id":"JY_002",
                                        "chargeType":"GOVERNMENT",
                                        "chargeCode":"JY",
                                        "country":"NG",
                                        "salePrice":"NGN1799"
                                    },
                                    {
                                        "id":"QT_001",
                                        "chargeType":"CARRIER_SURCHARGE",
                                        "chargeCode":"QT",
                                        "country":"NG",
                                        "salePrice":"NGN2345"
                                    }
                                ],
                            "carrier":{
                                "code":"H1",
                                "name":"Hahn Air System"
                                },
                            "cabin":"ECONOMY",
                            "mileage":"317",
                            "operatingDisclosure":"Operated by medview airlines",
                            "latestTicketingTime":"2017-10-04T20:00+01:00"
                            
                    }
                    
                }
                
                
                    
                    
                ]
            }
+ Response 401 (application/json)


    + Body

            {
                "status": "401",
                "data": "Unauthorized access"
            }
+ Response 404 (application/json)


    + Body

            {
                "status": "404",
                "data": "No flight data for search"
            }

## Search Round Trip Flight [/api/v1/search/flights/{roundTrip}]

### Search Round Trip Flight [POST]
With this endpoint you can search for flights going and returning to a location.
+ Request (application/json, )
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQwLCJuYW1lIjoic2F2YW5hIHNtYXJ0c2F2ZSIsImFjY291bnROdW1iZ
            

    + Body
                    
            {
                 "origin": "QUO",
                 "destination":"LOS",
                 "departure":"2017-10-04",
                 "return":"2017-10-05",
                 "options": [
                 {"times":{
                    "depart":"11:30",
                    "return":"15:00"
                    }
                 },
                 {"price":{
                    "currency":"NGN",
                    "below":"50,000"
                    }
                 },
                 {"airline":{
                    "carrierCode":"W3",
                    "carrierName":"Arik Airline",
                    "cabin":"first class"
                    }
                 },
                 {"passengers": {
                      "adultCount": 1,
                      "infantInLapCount": 0,
                      "infantInSeatCount": 0,
                      "childCount": 0,
                      "seniorCount": 0
                    }
                 },
                 {"extras":{
                     "stops":"0",
                     "refundable":"true"
                     }
                }
                ]
                 
            }
+ Response 201 (application/json)


    + Body

            {
                "status": "200",
                "data": [
                {
                    "stops":0,
                    "trip":{
                            
                            "aircraft":{
                                "code":"767",
                                "name":"Boeing 737"
                                },
                            "departure":{
                                "cityCode":"LOS",
                                "cityName":"Lagos",
                                "airport":"Lagos Murtaka Muhammed International"
                                },
                            "arrival":{
                                "cityCode":"ABV",
                                "cityName":"Abuja",
                                "airport":"Abuja Nnamd Azikiwe International"
                                },
                            
                            "booking":{
                                "id":"GI5njCtlByOCiRu4",
                                "code":"O",
                                "codeCount":9
                                },
                            "times":{
                                "departure":"2017-10-04T18:00+01:00",
                                "arrival":"2017-10-04T19:00+01:00",
                                "duration":68
                                },
                            "pricing":{
                                "baseFare":"USD100",
                                "salesFare":"NGN35983",
                                "salesTax":"NGN19701",
                                "saleTotal":"NGN55684"
                                },
                            "tax":[
                                    {
                                        "id":"JY_002",
                                        "chargeType":"GOVERNMENT",
                                        "chargeCode":"JY",
                                        "country":"NG",
                                        "salePrice":"NGN1799"
                                    },
                                    {
                                        "id":"QT_001",
                                        "chargeType":"CARRIER_SURCHARGE",
                                        "chargeCode":"QT",
                                        "country":"NG",
                                        "salePrice":"NGN2345"
                                    }
                                ],
                            "carrier":{
                                "code":"H1",
                                "name":"Hahn Air System"
                                },
                            "cabin":"",
                            "mileage":"",
                            "operatingDisclosure":"",
                            "latestTicketingTime":""
                            
                    }
                },
                {
                    "stops":2,
                    "trip1":{
                            
                            "aircraft":{
                                "code":"767",
                                "name":"Boeing 737"
                                },
                            "departure":{
                                "cityCode":"LOS",
                                "cityName":"Lagos",
                                "airport":"Lagos Murtaka Muhammed International"
                                },
                            "arrival":{
                                "cityCode":"ABV",
                                "cityName":"Abuja",
                                "airport":"Abuja Nnamd Azikiwe International"
                                },
                            
                            "booking":{
                                "id":"GI5njCtlByOCiRu4",
                                "code":"O",
                                "codeCount":9
                                },
                            "times":{
                                "departure":"2017-10-04T18:00+01:00",
                                "arrival":"2017-10-04T19:00+01:00",
                                "duration":68
                                },
                            "pricing":{
                                "baseFare":"USD100",
                                "salesFare":"NGN35983",
                                "salesTax":"NGN19701",
                                "saleTotal":"NGN55684"
                                },
                            "tax":[
                                    {
                                        "id":"JY_002",
                                        "chargeType":"GOVERNMENT",
                                        "chargeCode":"JY",
                                        "country":"NG",
                                        "salePrice":"NGN1799"
                                    },
                                    {
                                        "id":"QT_001",
                                        "chargeType":"CARRIER_SURCHARGE",
                                        "chargeCode":"QT",
                                        "country":"NG",
                                        "salePrice":"NGN2345"
                                    }
                                ],
                            "carrier":{
                                "code":"H1",
                                "name":"Hahn Air System"
                                },
                            "cabin":"",
                            "mileage":"",
                            "operatingDisclosure":"",
                            "latestTicketingTime":""
                            
                    },
                    "trip2":{
                            
                            "aircraft":{
                                "code":"767",
                                "name":"Boeing 737"
                                },
                            "departure":{
                                "cityCode":"LOS",
                                "cityName":"Lagos",
                                "airport":"Lagos Murtaka Muhammed International"
                                },
                            "arrival":{
                                "cityCode":"ABV",
                                "cityName":"Abuja",
                                "airport":"Abuja Nnamd Azikiwe International"
                                },
                            
                            "booking":{
                                "id":"GI5njCtlByOCiRu4",
                                "code":"O",
                                "codeCount":9
                                },
                            "times":{
                                "departure":"2017-10-04T18:00+01:00",
                                "arrival":"2017-10-04T19:00+01:00",
                                "duration":68
                                },
                            "pricing":{
                                "baseFare":"USD100",
                                "salesFare":"NGN35983",
                                "salesTax":"NGN19701",
                                "saleTotal":"NGN55684"
                                },
                            "tax":[
                                    {
                                        "id":"JY_002",
                                        "chargeType":"GOVERNMENT",
                                        "chargeCode":"JY",
                                        "country":"NG",
                                        "salePrice":"NGN1799"
                                    },
                                    {
                                        "id":"QT_001",
                                        "chargeType":"CARRIER_SURCHARGE",
                                        "chargeCde":"QT",
                                        "country":"NG",
                                        "salePrice":"NGN2345"
                                    }
                                ],
                            "carrier":{
                                "code":"H1",
                                "name":"Hahn Air System"
                                },
                            "cabin":"",
                            "mileage":"",
                            "operatingDisclosure":"",
                            "latestTicketingTime":""
                            
                    }
                    
                }
                
                
                    
                    
                ]
            }
+ Response 401 (application/json)


    + Body

            {
                "status": "401",
                "data": "Unauthorized access"
            }
+ Response 404 (application/json)


    + Body

            {
                "status": "404",
                "data": "No flight data for search"
            }